/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import io.ktor.server.application.Application
import io.ktor.server.application.ApplicationStopped
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import org.example.di.configureDI
import org.example.plugins.configureCors
import org.example.plugins.configureDatabase
import org.example.plugins.configureFrontend
import org.example.plugins.configureRouting
import org.example.plugins.configureSecurity
import org.example.plugins.configureSerialization
import org.example.plugins.configureStatusPages
import org.example.plugins.configureWebjar
import org.example.utils.cleanOldCache
import java.io.File
import kotlin.time.Duration.Companion.hours

fun main(args: Array<String>) {
    io.ktor.server.netty.EngineMain.main(args)
}

suspend fun Application.module() {
    val secret = environment.config.property("jwt.secret").getString()
    val issuer = environment.config.property("jwt.issuer").getString()
    val audience = environment.config.property("jwt.audience").getString()
    val realm = environment.config.property("jwt.realm").getString()

    configureDatabase()
    configureDI()
    configureCors()
    configureSerialization()
    configureWebjar()
    configureRouting(issuer, audience, secret)
    configureSecurity(realm, secret, issuer, audience)
    configureStatusPages()
    configureFrontend()

    val cleanJob = launch {
        while (true) {
            delay(24.hours)
            cleanOldCache(File("build/cache"), 7)
        }
    }

    monitor.subscribe(ApplicationStopped) {
        cleanJob.cancel()
    }
}
