ktor:
  application:
    modules:
      - org.example.AppKt.module
  deployment:
    port: 9000
    watch:
      - classes
      - resources
  development: true
session:
  secretEncryptionKey: $SESSION_SECRET_ENCRYPTION_KEY
  secretSigninKey: $SESSION_SECRET_SIGN_IN_KEY
jwt:
  secret: $JWT_SECRET
  domain: $JWT_DOMAIN
  audience: $JWT_AUDIENCE
  realm: $JWT_REALM
  issuer: $JWT_ISSUER

database:
  port: $DB_PORT
  driver: $DB_DRIVER
  db: $DATABASE
  user: $DB_USER
  password: $DB_PASSWORD
  poolSize: 10
  connectionTimeout: 30000
  idleTimeout: 600000
  maxLifetime: 1800000
  minimumIdle: 5
  leakDetectionThreshold: 60000
  cachePrepStmts: true
  prepStmtCacheSize: 250
  prepStmtCacheSqlLimit: 2048
  useServerPrepStmts: true
  runMigrations: false

pesapal:
  baseUrl: $PESAPAL_BASE_URL
  consumerKey: $PESAPAL_CONSUMER_KEY
  consumerSecret: $PESAPAL_CONSUMER_SECRET

google:
  clientID: $GOOGLE_CLIENT_ID
  clientSecret: $GOOGLE_CLIENT_SECRET

smtp:
  fromEmail: $SMTP_FROM_EMAIL
  host: $SMTP_HOST
  port: $SMTP_PORT
  username: $SMTP_USERNAME


