ktor:
  application:
    modules:
      - org.example.AppKt.module
  deployment:
    port: "$PORT:8080"
    watch:
      - classes
      - resources
  development: true
jwt:
  secret: $JWT_SECRET
  domain: $JWT_DOMAIN
  audience: $JWT_AUDIENCE
  realm: $JWT_REALM
  issuer: $JWT_ISSUER
database:
  port: $DB_PORT
  driver: $DB_DRIVER
  db: $DATABASE
  user: $DB_USER
  password: $DB_PASSWORD
  poolSize: 10