ALTER TABLE users ADD CONSTRAINT fk_users_role__id FOREIGN KEY ("role") REFERENCES roles(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE role_permissions ADD CONSTRAINT fk_role_permissions_role__id FOREIGN KEY ("role") REFERENCES roles(id) ON DELETE CASCADE ON UPDATE RESTRICT;
