CREATE TABLE IF NOT EXISTS users (id VARCHAR(10) NOT NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, "name" VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, "password" VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL);
ALTER TABLE users ADD CONSTRAINT users_id_unique UNIQUE (id);
